id = "gram"
name = "Gram Language Support"
version = "0.3.5"
schema_version = 1
authors = ["Gram Data Contributors"]
description = "Support for Gram notation - composable data patterns"

# path = "grammars/tree-sitter-gram"
[grammars.gram]
repository = "file:///Users/akollegger/Developer/gram-data/tree-sitter-gram"
rev = "e0870374d5adc6afd3ff937d6968c2123acee33f"
