id = "gram"
name = "Gram Language Support"
version = "0.3.7"
schema_version = 1
authors = ["Gram Data Contributors"]
description = "Support for Gram notation - composable data patterns"

capabilities = [
  { kind = "process:exec", command = "*", args = ["stdio"] },
  { kind = "download_file", host = "github.com", path = ["gram-data", "tree-sitter-gram", "**"] },
]

# path = "grammars/tree-sitter-gram"
[grammars.gram]
repository = "https://github.com/gram-data/tree-sitter-gram"
rev = "746afa9e990c3deca83dc2a2638877aef4bef4fa"
