id = "gram"
name = "Gram Language Support"
version = "0.3.5"
schema_version = 1
authors = ["Gram Data Contributors"]
description = "Support for Gram notation - composable data patterns"

# path = "grammars/tree-sitter-gram"
[grammars.gram]
repository = "file:///Users/akollegger/Developer/gram-data/tree-sitter-gram"
rev = "a9e52f940500b0766ede0ac976b094158f52c52f"
