name = "Gram"
grammar = "gram"
path_suffixes = ["gram"]
autoclose_before = ")]}'\":.,;>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
]
word_characters = ["_"]

[prettier]
allowed = false

# [language_servers]
# Add language server configuration here if you develop one for Gram
